# Push/Pull RequestされるごとにESLintを実行する。
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  YARN_CACHE_FOLDER: .cache/yarn

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node env
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node }}
          check-latest: true

      - name: Cache node_modules
        uses: actions/cache@v2.1.4
        id: yarn-cache
        with:
          path: ${YARN_CACHE_FOLDER}
          key: ${{ runner.os }}-yarn-v1

      - name: Install dependencies
        run: yarn

      - nameRun linter
        run: yarn lint

